// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoScrollController from "./auto_scroll_controller"
application.register("autoscroll", AutoScrollController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)
